# docker-compose.ghcr.yml
# 前端和 API 服务 - 从 GHCR 拉取预构建镜像
name: avatar-mgmt-app

services:
  # API Server - 从 GHCR 拉取
  api:
    image: ghcr.io/${GITHUB_REPOSITORY:-rayhu/avatar-mgmt}/api:${IMAGE_TAG:-latest}
    restart: always
    env_file:
      - .env.api
    ports:
      - "3000:3000"
    networks:
      - jc21-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend - 从 GHCR 拉取
  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY:-rayhu/avatar-mgmt}/frontend:${IMAGE_TAG:-latest}
    restart: always
    env_file:
      - .env.frontend
    environment:
      # 动态环境变量
      - VITE_APP_VERSION=${IMAGE_TAG:-latest}
    ports:
      - "4173:80"
    networks:
      - jc21-network

# 引用 JC21 的网络
networks:
  jc21-network:
    external: true
    name: avatar-mgmt-jc21-network
