# 本地开发测试使用，不绑定内部网络，不使用nginx-proxy-manager
name: avatar-mgmt-dev

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: directus
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U directus"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Directus CMS
  directus:
    image: directus/directus:11.8
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
      - ./directus/db_json:/directus/db_json
      - ./directus/schemas:/directus/schemas
    ports:
      - "8055:8055"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:8055/"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 120s

