version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env.prod
    environment:
      POSTGRES_DB: directus
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - internal

  directus:
    image: directus/directus:10
    restart: always
    depends_on:
      - db
    env_file:
      - .env.prod
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
      - ./directus/schemas:/directus/schemas
    expose:
      - "8055"
    networks:
      - internal

  api:
    build:
      context: .
      dockerfile: api-server/Dockerfile
    restart: always
    depends_on:
      - directus
    env_file:
      - .env.prod
    expose:
      - "3000"
    networks:
      - internal

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal

networks:
  internal:
    driver: bridge 
