# 统一的网络配置，用于Staging和Production服务
name: avatar-mgmt-jc21

services:
  # Nginx Proxy Manager
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'        # HTTP (标准端口)
      - '443:443'      # HTTPS (标准端口)
      - '81:81'        # Admin UI
    volumes:
      - ./jc21/data:/data
      - ./jc21/letsencrypt:/etc/letsencrypt
    networks:
      - jc21-network   # 添加网络
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:81"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Database for Nginx Proxy Manager
  nginx-proxy-manager-db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./jc21/data/mysql:/var/lib/mysql
    networks:
      - jc21-network   # 添加网络
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

# 添加网络定义
networks:
  jc21-network:
    driver: bridge
    name: avatar-mgmt-jc21-network  # 固定网络名称
