# docker-compose.db.yml
# 数据库和 Directus CMS 服务
name: avatar-mgmt-db

services:
  # PostgreSQL Database
  db:
    image: postgres:15.7            # 固定小版本，避免隐形升级
    restart: always
    env_file:
      - .env.directus
    environment:
      POSTGRES_DB: directus
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data   # ← 命名卷（核心变化）
    networks:
      - jc21-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U directus"]
      interval: 30s
      timeout: 10s
      retries: 10

  directus:
    image: directus/directus:11.8.0  # 固定小版本
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.directus
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
      - ./directus/schemas:/directus/schemas
    ports:
      - "8055:8055"
    networks:
      - jc21-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:8055/"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 120s

networks:
  jc21-network:
    external: true
    name: avatar-mgmt-jc21-network

volumes:
  db_data: {}   # ← 新增命名卷声明
