/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommentList: typeof import('./components/CommentList.vue')['default']
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    LikeButton: typeof import('./components/LikeButton.vue')['default']
    ModelGallerySkeleton: typeof import('./components/ModelGallerySkeleton.vue')['default']
    ModelListSkeleton: typeof import('./components/ModelListSkeleton.vue')['default']
    ModelVersionList: typeof import('./components/ModelVersionList.vue')['default']
    ModelViewer: typeof import('./components/ModelViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SSMLViewer: typeof import('./components/SSMLViewer.vue')['default']
  }
}
