name: Format Check

on:
  pull_request:
    paths:
      - 'frontend/src/**/*.{js,ts,vue}'
      - 'frontend/src/**/*.{json,md}'
  push:
    branches:
      - main
    paths:
      - 'frontend/src/**/*.{js,ts,vue}'
      - 'frontend/src/**/*.{json,md}'

jobs:
  format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: yarn install
      
      - name: Check formatting
        id: format-check
        run: yarn format:check
        continue-on-error: true
      
      - name: Format files
        if: failure()
        run: yarn format
      
      - name: Create Pull Request
        if: failure()
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'style: format code'
          title: 'style: format code'
          body: |
            This PR contains formatting fixes for the following files:
            ${{ steps.format-check.outputs.formatted_files }}
          branch: format-code
          base: ${{ github.head_ref }}
          delete-branch: true 
