name: i18n-check

on:
  pull_request:
    paths:
      - 'frontend/src/**/*.vue'
      - 'frontend/src/locales/*.ts'
      - 'frontend/src/locales/*.json'
  push:
    branches:
      - main
    paths:
      - 'frontend/src/**/*.vue'
      - 'frontend/src/locales/*.ts'
      - 'frontend/src/locales/*.json'
  schedule:
    - cron: '0 0 * * 1'  # 每周一凌晨执行

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: yarn install
      
      - name: Check i18n
        id: i18n-check
        run: yarn i18n:check
        continue-on-error: false
      
      - name: Generate i18n report
        if: always()
        run: yarn i18n:report
      
      - name: Upload i18n report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: i18n-report
          path: frontend/reports/i18n-report.json
          retention-days: 30
      
      - name: Comment PR
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const report = require('./frontend/reports/i18n-report.json');
            const issues = report.issues.map(issue => 
              `- ${issue.type}: ${issue.message} (${issue.file}:${issue.line})${issue.suggestion ? `\n  Suggestion: ${issue.suggestion}` : ''}`
            ).join('\n');
            
            const summary = report.summary;
            const body = `## i18n 检查失败\n\n` +
              `### 问题统计\n` +
              `- 总问题数: ${summary.totalIssues}\n` +
              `- 缺失翻译: ${summary.missingKeys}\n` +
              `- 未使用翻译: ${summary.unusedKeys}\n` +
              `- 硬编码文本: ${summary.hardcodedStrings}\n` +
              `- 格式问题: ${summary.formatIssues}\n\n` +
              `### 详细问题\n\n${issues}\n\n` +
              `请修复这些问题后重新提交。\n\n` +
              `完整报告可在构建产物中下载。`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
      
      - name: Create Issue for Weekly Report
        if: github.event_name == 'schedule' && failure()
        uses: actions/github-script@v7
        with:
          script: |
            const report = require('./frontend/reports/i18n-report.json');
            const issues = report.issues.map(issue => 
              `- ${issue.type}: ${issue.message} (${issue.file}:${issue.line})${issue.suggestion ? `\n  Suggestion: ${issue.suggestion}` : ''}`
            ).join('\n');
            
            const summary = report.summary;
            const body = `## 每周 i18n 检查报告\n\n` +
              `### 问题统计\n` +
              `- 总问题数: ${summary.totalIssues}\n` +
              `- 缺失翻译: ${summary.missingKeys}\n` +
              `- 未使用翻译: ${summary.unusedKeys}\n` +
              `- 硬编码文本: ${summary.hardcodedStrings}\n` +
              `- 格式问题: ${summary.formatIssues}\n\n` +
              `### 详细问题\n\n${issues}\n\n` +
              `请团队关注并处理这些问题。\n\n` +
              `完整报告可在构建产物中下载。`;
            
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `[i18n] 每周检查报告 - ${new Date().toISOString().split('T')[0]}`,
              body: body,
              labels: ['i18n', 'report']
            }); 
