name: i18n-check

on:
  pull_request:
    paths:
      - 'frontend/src/**/*.vue'
      - 'frontend/src/locales/*.json'

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: yarn install
      
      - name: Check i18n
        id: i18n-check
        run: yarn i18n:check
        continue-on-error: false
      
      - name: Generate i18n report
        if: failure()
        run: yarn i18n:report
      
      - name: Upload i18n report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: i18n-report
          path: frontend/reports/i18n-report.json
      
      - name: Comment PR
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const report = require('./frontend/reports/i18n-report.json');
            const issues = report.issues.map(issue => 
              `- ${issue.type}: ${issue.message} (${issue.file}:${issue.line})`
            ).join('\n');
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## i18n 检查失败\n\n发现以下问题：\n\n${issues}\n\n请修复这些问题后重新提交。`
            }); 